sonar.projectKey=sofiaschanton_insight-commerce-recsys
sonar.organization=sofiaschanton

sonar.projectName=insight-commerce-recsys
sonar.projectVersion=1.0

# Fuentes a analizar
sonar.sources=src
sonar.tests=tests

# Cobertura
sonar.python.coverage.reportPaths=coverage.xml

# Exclusiones
sonar.exclusions=**/__pycache__/**,**/*.pyc,data/**,models/**,notebooks/**,reports/**

# Encoding
sonar.sourceEncoding=UTF-8
